// ─── Deployments loader ─────────────────────────────────────────────────
// Reads deployments.json (generated by blockchain/ethereum/scripts/deploy.js)
// at app boot and exposes addresses keyed by chainId. Replaces the previous
// pattern of manually editing constants.js after every deploy.
//
// Usage (in the browser):
//   import { loadDeployments, getAddresses } from '/js/blockchain/deployments-loader.js';
//   await loadDeployments();
//   const { DexHerosManager, DexheroToken } = getAddresses(chainId);

let _cache = null;

export async function loadDeployments(url = '/deployments.json') {
    if (_cache) return _cache;
    try {
        const res = await fetch(url, { cache: 'no-store' });
        if (!res.ok) throw new Error(`HTTP ${res.status}`);
        _cache = await res.json();
        return _cache;
    } catch (err) {
        console.warn('[Deployments] Failed to load deployments.json — falling back to constants.js:', err.message);
        _cache = {};
        return _cache;
    }
}

export function getAddresses(chainId) {
    if (!_cache) {
        throw new Error('[Deployments] Call loadDeployments() before getAddresses().');
    }
    const entry = _cache[String(chainId)] || _cache[chainId];
    if (!entry) return null;
    return entry.addresses || null;
}

export function getDeployment(chainId) {
    if (!_cache) {
        throw new Error('[Deployments] Call loadDeployments() before getDeployment().');
    }
    return _cache[String(chainId)] || _cache[chainId] || null;
}

export function getKnownChainIds() {
    return _cache ? Object.keys(_cache).map(Number) : [];
}
